version: '2'
services:
  web:
    build: .
    ports:
      - "3002:3000"
    links:
      - db:db
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - "authydbdata:/var/lib/postgresql/data"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  authydbdata:
    driver: local


